### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by voidfyre1** [joedf/HWSEdit#6]
Is this still being worked on? I'd like to try it, but hybrid analysis detects some malware, so I'd like to know if it's just a false positive. 

Also, it seems like the game has been updated since.

Regards.

**Comment by joedf** [comment]
Hi there!

Glad to see there's still interest!
I haven't touch this or the game in a while. You're welcome to make changes, pull requests or even fork the Complete project.

**Comment by Joostarr** [comment]
Hi!

I know absolutely nothing about coding, so I can't even attempt to do something lol!

I don't know if the tool still works. I downloaded it and hybrid analysis tells me it contains malware, so I've been wary of running it, hence why I was asking you.

I did run another tool found on the forums which used your code that another user made, but the profile doesn't work, apparently because I'm playing with a Sorcerer and it seems to be one of the newer classes.

I'll give yours a check since you say it's safe. And yes, I'm sure there's always that random guy interested in these things every once in a blue moon.

Regards.

**Comment by joedf** [comment]
Perhaps I could take a look at this other tool, do you have a link?
Assuming the save format hasn't changed much, adding a new character class should be relatively straight forward.

**Comment by Joostarr** [comment]
I tried with yours and I get the same error. It's the same program, just some guy did a few upgrades, it's in the original thread you did for the program on the Hammerwatch forums.

**Comment by joedf** [comment]
Closed. Still alive-ish. 😬
